name: Publish

on:
  push:
    paths:
      - '.github/workflows/ansible.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - run: curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
      - run: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
      - run: sudo add-apt-repository --yes --update ppa:ansible/ansible
      - run: sudo apt update
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ansible cloudflare-warp

      - run: warp-cli teams-enroll -h

      - name: Start SSH agent
        run: ssh-agent -a ${{ runner.temp }}/ssh_agent.sock
      - name: Add SSH keys
        run: |
          echo "${{ secrets.PK_NAS2 }}" | ssh-add -t 15m -
        env:
          SSH_AUTH_SOCK: ${{ runner.temp }}/ssh_agent.sock

      - uses: actions/checkout@v3
      # - run: ansible-playbook -i hosts.yml playbooks/initial.yaml
      #   env:
      #     SSH_AUTH_SOCK: ${{ runner.temp }}/ssh_agent.sock